config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get '/robots.txt' => RobotsTxt
  use_doorkeeper

  #get 'test_gauge', to: 'test#gauge'

  admin = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  constraints admin do
    mount Sidekiq::Web => '/sidekiq'
    ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  end

  namespace :api do
    resources :external_graders,
      only: [:create, :show, :update] do
        get :challenge_config, on: :collection
        get :presign, on: :member
        get :submission_info, on: :member
    end
    get 'mailchimps/webhook' => 'mailchimps#verify',
      as: :verify_webhook
    post 'mailchimps/webhook' => 'mailchimps#webhook',
      as: :update_webhook
    resources :clef_tasks, only: [:show]
    get 'user', to: 'oauth_credentials#show'
    resources :challenges, only: [:index, :show] do
      resources :submissions, only: :index
    end
    resources :participants, only: :show
    resources :submissions, only: :show
  end

  namespace :components do
    resources :notifications, only: [:index]
  end

  devise_for :participants
  resources :participants, only: [:show, :edit, :update, :destroy, :index] do
    get :sync_mailchimp
    get :regen_api_key
    get :remove_image
    resources :email_preferences, only: [:edit, :update]
  end
  resources :job_postings, only: [:index, :show]
  resources :gdpr_exports, only: [:create]

  resources :landing_page, only: [:index]
  match '/landing_page/host', to: 'landing_page#host', via: :get

  resources :organizer_applications, only: [:create]
  resources :organizers, except: [:new, :index] do
    resources :challenges
    get :remove_image
    get :regen_api_key
    get :clef_email
    resources :clef_tasks
    resources :members
  end
  resources :blogs do
    resources :votes, only: [:create, :destroy]
  end

  resources :clef_tasks do
    resources :task_dataset_files
  end

  resources :participant_clef_tasks

  resources :task_dataset_files do
    resources :task_dataset_file_downloads
  end

  resources :challenges, only: [:index,:show] do
    resources :dataset_files
    resources :participant_challenges, only: [:index] do
      get :approve, on: :collection
      get :deny, on: :collection
    end
    resources :events
    resources :winners, only: [:index]
    resources :submissions do
      post :filter, on: :collection
    end
    resources :dynamic_contents, only: [:index]
    resources :leaderboards, only: :index do
      get :submission_detail
    end
    resources :topics, except: [:show]
    get :regrade
    get :remove_image
    get :clef_task
    resources :votes, only: [:create, :destroy]
    resources :follows, only: [:create, :destroy]
    resources :invitations, only: [] do
      collection { post :import }
    end
    resources :dataset_terms, only: [:update]
  end
  get '/load_more_challenges', to: 'challenges#load_more', as: :load_more_challenges

  resources :dataset_files, only: [] do
    resources :dataset_file_downloads, only: [:create]
  end

  resources :submissions, only: [] do
    resources :submission_comments, only: [:create, :delete, :edit, :update]
  end

  resources :submission_comments, only: [] do
    resources :votes, only: [:create, :destroy]
  end

  resources :topics do
    resources :comments, only: [:new, :create, :edit, :destroy, :update] do
      get :quote
    end
    resources :votes, only: [:create, :destroy]
  end
  match '/topics/:topic_id/discussion', to: 'comments#new', via: :get, as: :new_topic_discussion


  resources :comments, only: [] do
    resources :votes, only: [:create, :destroy]
  end

  resources :articles do
    resources :article_sections
    resources :votes, only: [:create, :destroy]
    get :remove_image
  end
  get '/load_more_articles', to: 'articles#load_more', as: :load_more_articles

  match '/contact', to: 'pages#contact', via: :get
  match '/privacy', to: 'pages#privacy', via: :get
  match '/terms',   to: 'pages#terms',   via: :get
  match '/faq',     to: 'pages#faq',     via: :get
  match '/cookies', to: 'pages#cookies', via: :get


  resources :markdown_editors, only: [:index, :create] do
    put :presign, on: :collection
  end

  resources :challenge_calls, only: [] do
    resources :challenge_call_responses, only: [:create]
  end
  get '/call-for-challenges/:challenge_call_id/apply' => 'challenge_call_responses#new', as: 'challenge_call_apply'
  get '/call-for-challenges/:challenge_call_id/applications/:id' => 'challenge_call_responses#show', as: 'challenge_call_show'
  get 'SDSC' => 'challenge_call_responses#new', challenge_call_id: 3

  root 'landing_page#index'

  # catch all
  get '*short', to: 'short_urls#show'
end

app/models/leaderboard/base_leaderboard.rb
class BaseLeaderboard < ApplicationRecord
  belongs_to :challenge
  belongs_to :challenge_round
  belongs_to :participant, optional: true

  as_enum :leaderboard_type,
    [:leaderboard, :ongoing, :previous, :previous_ongoing],
    map: :string
end

app/models/leaderboard/leaderboard.rb
class Leaderboard < SqlView
  self.primary_key = :id
  after_initialize :readonly!

  belongs_to :challenge
  belongs_to :participant
  belongs_to :challenge_round

  default_scope { order(seq: :asc) }
end

app/models/leaderboard/ongoing_leaderboard.rb
class OngoingLeaderboard < SqlView
  self.primary_key = :id
  after_initialize :readonly!

  belongs_to :challenge
  belongs_to :participant

  default_scope { order(seq: :asc) }
end

app/models/leaderboard/previous_leaderboard.rb
class PreviousLeaderboard < SqlView
  self.primary_key = :id
  after_initialize :readonly!
end

app/models/leaderboard/previous_ongoing_leaderboard.rb
class PreviousOngoingLeaderboard < SqlView
  self.primary_key = :id
  after_initialize :readonly!
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :authenticate_participant!,
    except: :index
  before_action :set_challenge
  respond_to :js, :html
  layout :set_layout

  def index
    @current_round = current_round
    if @challenge.completed?
      if params[:post_challenge] == 'on'
        @post_challenge = 'on'
      else
        @post_challenge = 'off'
      end
    end
    if @current_round.blank?
      current_round_id = 0
    else
      current_round_id = @current_round.id
    end
    if @post_challenge == 'on'
      @leaderboards = policy_scope(OngoingLeaderboard)
          .where(challenge_round_id: current_round_id)
          .page(params[:page])
          .per(10)
          .order(:seq)
    else
      @leaderboards = policy_scope(Leaderboard)
          .where(challenge_round_id: current_round_id)
          .page(params[:page])
          .per(10)
          .order(:seq)
    end
  end

  def submission_detail
    leaderboard = Leaderboard.find(params[:leaderboard_id])
    @leaderboard = @challenge.leaderboards
    @submissions = Submission
      .where(
        participant_id: params[:participant_id],
        challenge_id: params[:challenge_id],
        challenge_round_id: leaderboard.challenge_round_id)
      .order(created_at: :desc)
    render js: concept(
      Leaderboard::Cell,
      @leaderboard,
      challenge: @challenge,
      submissions: @submissions).(:insert_submissions)
  end

  private
  def set_challenge
    @challenge = Challenge.friendly.find(params[:challenge_id])
  end

  def current_round
    if params[:challenge_round_id].present?
      ChallengeRound.find(params[:challenge_round_id].to_i)
    else
      @challenge.challenge_rounds.where(active: true).first
    end
  end

  def set_layout
    return 'bare' if action_name == 'show'
    return 'application'
  end

end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper

  def status_badge(status)
    case status
    when 'ready','submitted','initialized'
      klass = 'badge-amber'
    when 'graded'
      klass = 'badge-green'
    when 'failed'
      klass = 'badge-red'
    else
      klass = 'badge-amber'
    end

    %Q[
      <div class="#{klass}">
        <span class="badge-square"></span>
        <span class="badge-text">
          #{status.capitalize}
        </span>
      </div>
    ].html_safe
  end

  def ranking_change_helper(entry)
    if entry.previous_row_num == 0 || entry.previous_row_num == entry.row_num
      output =  "<td class='change'>" +
                    image_tag(
                      "icon-change-none.csv",
                      data: { toggle: 'tooltip'},
                      title: '0 change') +
                "</td>"
      return output
    end

    if entry.row_num > entry.previous_row_num
      output =  "<td class='change'>" +
                    image_tag(
                      "icon-change-up.csv",
                      data: { toggle: 'tooltip'},
                      title: "+#{entry.row_num - entry.previous_row_num} change") +
                "</td>"
      return output
    end

    if entry.row_num < entry.previous_row_num && entry.previous_row_num != 0
      output =  "<td class='change'>" +
                    image_tag(
                      "icon-change-down.csv",
                      data: { toggle: 'tooltip'},
                      title: "-#{entry.previous_row_num - entry.row_num} change") +
                "</td>"
      return output
    end
  end

end

app/views/leaderboards/_leaderboards.html.erb
<%= concept(Leaderboard::Cell::TableRow,
      collection: @leaderboards,
      challenge: @challenge,
      current_round: @current_round,
      current_participant: current_participant) %>

app/views/leaderboards/_post_challenge_off.html.erb
<div class="row">
  <form class="leaderboard">
    <%= link_to challenge_leaderboards_path(challenge, post_challenge: 'on') do %>
      <input type="checkbox" id="switch" name="switch" class="switch">
      <label for="switch">Show post-challenge submissions</label>
    <% end %>
  </form>
  <p class="light">Entries column includes entries not yet graded which, when graded, may affect the contents of this leaderboard.</p>
</div>

app/views/leaderboards/_post_challenge_on.html.erb
<div class="row">
  <form class="leaderboard">
    <%= link_to challenge_leaderboards_path(challenge) do %>
      <input type="checkbox" id="switch" name="switch" class="switch" checked>
      <label for="switch" data-on="Yes" data-off="No">Show post-challenge submissions</label>
    <% end %>
  </form>
  <p class="light">Entries column includes entries not yet graded which, when graded, may affect the contents of this leaderboard.</p>
</div>

app/views/leaderboards/index.html.erb
<div class='content'>
  <%= concept(Challenge::Cell::ChallengeMasthead,
                @challenge,
                current_participant: current_participant) %>
  <%= render partial: 'challenges/show/subnav',
        locals: { challenge: @challenge } %>
  <%= concept(Leaderboard::Cell::ChallengeRoundPills,
                @challenge,
                current_round: @current_round,
                current_participant: current_participant) %>

  <% if @current_round.leaderboard_note.present? %>
    <div class='row'>
      <div class="leaderboard-note">
        <%= sanitize(@current_round.leaderboard_note) %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <% if policy(@challenge).show_leaderboard? %>
      <% unless @challenge.show_leaderboard? %>
        <div class="leaderboard-important-msg">
          <p>Leaderboard is only visible to organizers</p>
        </div>
      <% end %>
      <table class="leaderboard">
          <%= concept(Leaderboard::Cell::TableHead,
                @leaderboards,
                challenge: @challenge,
                current_round: @current_round,
                current_participant: current_participant) %>
          <tbody>
            <%= render partial: 'leaderboards' %>
          </tbody>
      </table>
    <% else %>
      <div class="leaderboard-msg">
        <p>Leaderboard is not displayed yet.</p>
      </div>
    <% end %>
  </div>

  <% if @post_challenge == 'off' %>
    <%= render partial: 'post_challenge_off',
          locals: { challenge: @challenge } %>
  <% end %>
  <% if @post_challenge == 'on' %>
    <%= render partial: 'post_challenge_on',
          locals: { challenge: @challenge } %>
  <% end %>

  <span id='more-anchor'></span>
  <%= render partial: 'shared/load_more',
        locals: { collection: @leaderboards } %>
  <div id='modal-anchor'></div>
</div>

app/views/leaderboards/index.js.erb
$(".load-more").remove();
$("table.leaderboard").append("<%= j render partial: 'leaderboards' %>");
$("#more-anchor").after("<%= j render partial: 'shared/load_more', locals: { collection: @leaderboards } %>");
$('html, body').animate({
   scrollTop: $(document).height()-$(window).height()},
   1400,
   "easeOutQuint"
);

app/views/leaderboards/show.html.erb
<div class="detail">
  <div class="detail-header-bg"></div>
  <%= link_to challenge_leaderboards_path(@entry.challenge_id) do %>
    <i class="fa fa-times" aria-hidden="true"></i>
  <% end %>

  <div class="row">
    <%= render partial: 'leaderboards/show/header',
          locals: {
            challenge: @challenge,
            participant: @participant,
            entry: @entry,
            submission_id: @entry.submission_id } %>

    <%= render partial: 'leaderboards/show/share',
          locals: { submission: @submission }%>

    <%= render partial: 'leaderboards/show/entry_description',
          locals: { entry: @entry, submission: @submission }  %>

    <% if @grader_logs.present? %>
      <%= render partial: 'submissions/show/codemirror' %>
    <% end %>

    <%= render partial: 'leaderboards/show/comments',
          locals: {
            submission: @submission,
            entry: @entry } %>
  </div>
  <%= render partial: 'leaderboards/show/meta',
        locals: { submission: @submission } %>
</div>