config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get '/robots.txt' => RobotsTxt
  use_doorkeeper

  #get 'test_gauge', to: 'test#gauge'

  admin = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  constraints admin do
    mount Sidekiq::Web => '/sidekiq'
    ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  end

  namespace :api do
    resources :external_graders,
      only: [:create, :show, :update] do
        get :challenge_config, on: :collection
        get :presign, on: :member
        get :submission_info, on: :member
    end
    get 'mailchimps/webhook' => 'mailchimps#verify',
      as: :verify_webhook
    post 'mailchimps/webhook' => 'mailchimps#webhook',
      as: :update_webhook
    resources :clef_tasks, only: [:show]
    get 'user', to: 'oauth_credentials#show'
    resources :challenges, only: [:index, :show] do
      resources :submissions, only: :index
    end
    resources :participants, only: :show
    resources :submissions, only: :show
  end

  namespace :components do
    resources :notifications, only: [:index]
  end

  devise_for :participants
  resources :participants, only: [:show, :edit, :update, :destroy, :index] do
    get :sync_mailchimp
    get :regen_api_key
    get :remove_image
    resources :email_preferences, only: [:edit, :update]
  end
  resources :job_postings, only: [:index, :show]
  resources :gdpr_exports, only: [:create]

  resources :landing_page, only: [:index]
  match '/landing_page/host', to: 'landing_page#host', via: :get

  resources :organizer_applications, only: [:create]
  resources :organizers, except: [:new, :index] do
    resources :challenges
    get :remove_image
    get :regen_api_key
    get :clef_email
    resources :clef_tasks
    resources :members
  end
  resources :blogs do
    resources :votes, only: [:create, :destroy]
  end

  resources :clef_tasks do
    resources :task_dataset_files
  end

  resources :participant_clef_tasks

  resources :task_dataset_files do
    resources :task_dataset_file_downloads
  end

  resources :challenges, only: [:index,:show] do
    resources :dataset_files
    resources :participant_challenges, only: [:index] do
      get :approve, on: :collection
      get :deny, on: :collection
    end
    resources :events
    resources :winners, only: [:index]
    resources :submissions do
      post :filter, on: :collection
    end
    resources :dynamic_contents, only: [:index]
    resources :leaderboards, only: :index do
      get :submission_detail
    end
    resources :topics, except: [:show]
    get :regrade
    get :remove_image
    get :clef_task
    resources :votes, only: [:create, :destroy]
    resources :follows, only: [:create, :destroy]
    resources :invitations, only: [] do
      collection { post :import }
    end
    resources :dataset_terms, only: [:update]
  end
  get '/load_more_challenges', to: 'challenges#load_more', as: :load_more_challenges

  resources :dataset_files, only: [] do
    resources :dataset_file_downloads, only: [:create]
  end

  resources :submissions, only: [] do
    resources :submission_comments, only: [:create, :delete, :edit, :update]
  end

  resources :submission_comments, only: [] do
    resources :votes, only: [:create, :destroy]
  end

  resources :topics do
    resources :comments, only: [:new, :create, :edit, :destroy, :update] do
      get :quote
    end
    resources :votes, only: [:create, :destroy]
  end
  match '/topics/:topic_id/discussion', to: 'comments#new', via: :get, as: :new_topic_discussion


  resources :comments, only: [] do
    resources :votes, only: [:create, :destroy]
  end

  resources :articles do
    resources :article_sections
    resources :votes, only: [:create, :destroy]
    get :remove_image
  end
  get '/load_more_articles', to: 'articles#load_more', as: :load_more_articles

  match '/contact', to: 'pages#contact', via: :get
  match '/privacy', to: 'pages#privacy', via: :get
  match '/terms',   to: 'pages#terms',   via: :get
  match '/faq',     to: 'pages#faq',     via: :get
  match '/cookies', to: 'pages#cookies', via: :get


  resources :markdown_editors, only: [:index, :create] do
    put :presign, on: :collection
  end

  resources :challenge_calls, only: [] do
    resources :challenge_call_responses, only: [:create]
  end
  get '/call-for-challenges/:challenge_call_id/apply' => 'challenge_call_responses#new', as: 'challenge_call_apply'
  get '/call-for-challenges/:challenge_call_id/applications/:id' => 'challenge_call_responses#show', as: 'challenge_call_show'
  get 'SDSC' => 'challenge_call_responses#new', challenge_call_id: 3

  root 'landing_page#index'

  # catch all
  get '*short', to: 'short_urls#show'
end

app/models/clef_task.rb
class ClefTask < ApplicationRecord
  belongs_to :organizer
  has_many :challenges
  has_many :challenge_participants, dependent: :destroy
  has_many :participant_clef_tasks,       dependent: :destroy
  has_many :task_dataset_files, inverse_of: :clef_task, dependent: :destroy
  accepts_nested_attributes_for :task_dataset_files,
                                reject_if: :all_blank,
                                allow_destroy: true
  validates_presence_of :task
  mount_uploader :eua_file, EuaUploader
  validates :eua_file, file_size: { less_than: 10.megabytes }

  as_enum :status, [:unregistered, :requested, :registered, :submitted], map: :string
  # also 'profile_incomplete' if profile is complete and this record doesn't exist
  # 'unregistered' if the profile is incomplete (& this record doesn't exist)

  def eua_required?
    self.eua_file.present?
  end
end

app/controllers/api/clef_tasks_controller.rb
class Api::ClefTasksController < Api::BaseController
  before_action :auth_by_api_key, only: [:show]

  def show  # GET :id
    begin
      clef_task = ClefTask.find(params[:id])
      # get clef participants with optional paramater status
      message = clef_participants(clef_task, params[:status])
      status = :ok
    rescue ActiveRecord::RecordNotFound
      status = :not_found
      message = "clef_task_id #{params[:id]} not found"
    rescue => e
      message = e
    ensure
      Rails.logger.info "API: #{message}"
      render :json => {message: message}, :include =>
        {:participant => {:only => [:email,:name,:affiliation,:first_name,:last_name,:address,:city,:country_cd]}},
          :except => [:created_at, :updated_at, :eua_file, :id, :approved], status:status
    end
  end

  def clef_participants(clef_task, status_cd)
    participant_clef_tasks = clef_task.participant_clef_tasks.includes(:participant)
    if status_cd.present?
      return participant_clef_tasks.where({status_cd: status_cd});
    end
    return participant_clef_tasks
  end

end

app/controllers/clef_tasks_controller.rb
class ClefTasksController < ApplicationController
  before_action :authenticate_participant!
  before_action :set_organizer
  before_action :set_clef_task, only: [:edit, :update, :destroy, :show]
  before_action :set_s3_direct_post, only: [:new, :create, :edit]

  def index
    @clef_tasks = @organizer.clef_tasks
    @challenges = @organizer.challenges
  end

  def show
  end

  def new
    @clef_task = @organizer.clef_tasks.new
  end

  def edit
    authorize @clef_task
  end

  def create
    @clef_task = @organizer.clef_tasks.new(clef_task_params)
    authorize @clef_task

    if @clef_task.save
      redirect_to organizer_clef_tasks_path(@organizer)
    else
      render :new
    end
  end

  def update
    if @clef_task.update(clef_task_params)
      redirect_to organizer_clef_tasks_path(@organizer)
    else
      render :edit
    end
  end

  def destroy
    @clef_task.destroy
    redirect_to organizer_clef_tasks_path(@organizer)
  end

  private
  def set_organizer
    @organizer = Organizer.friendly.find(params[:organizer_id])
  end

  def set_clef_task
    @clef_task = ClefTask.find(params[:id])
  end

  def clef_task_params
    params.require(:clef_task)
          .permit(:task,
                  :eua_file,
                  task_dataset_files_attributes: [
                    :id, :_destroy, :title, :dataset_file_s3_key
                  ])
  end

  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "task_dataset_files/organizer_#{@organizer.id}/#{SecureRandom.uuid}_${filename}",
                                               success_action_status: '201',
                                               acl: 'private')
  end

end

app/views/clef_tasks/_dataset_file.html.erb
<li>
  <div class="details">
    <h5><a href="#">Dataset Title</a></h5>
    <p class="description">Brief description here...</p>
  </div>
  <div class="stats">
    <div class="stat-fr">
      File Size<br>
      <span>287KB</span>
    </div>
    <div class="stat-fr">
      File Format<br>
      <span>PDF</span>
    </div>
  </div>
</li>

app/views/clef_tasks/_form.html.erb
<div class="row">
  <%= form_for [@organizer,@clef_task],
        validate: true,
        html: { class: 'sgl-col' } do |f| %>
    <fieldset>
      <label>Task</label>
      <%= f.text_field :task %>
      <label>End User Agreement file</label>
      <div class="upload">
        <% if @clef_task.eua_file.file.present? %>
          <span>You have already uploaded an EUA. If you wish to replace it, you can upload a new file</span>
          <%= link_to 'Current EUA', @clef_task.eua_file.file.url %>
        <% else %>
          <span>If this dataset requires an End User Agreement, you can upload it here</span>
        <% end %>
        <%= f.file_field :eua_file, class: 'file-upload' %>
        <span>PDF only, 5MB limit</span>
      </div>
    </fieldset>

    <fieldset>
      <div class="button-group">
        <%= f.button (@clef_task.new_record? ? 'Add Task' : 'Update Task'), class: 'btn btn-primary' %>
        <%= link_to organizer_path(@organizer), class: "btn btn-secondary", validate: false do %>
          Cancel
        <% end %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/clef_tasks/_task_dataset_file_fields.html.erb
<div class='nested-fields'>
  <fieldset>
    <label>File Title</label>
    <%= f.text_field :title %>
    <label>File Description</label>
    <%= f.text_field :description %>
    <label>Dataset file</label>
    <%= f.file_field :dataset_file_s3_key, class: 'file-upload s3File' %>
  </fieldset>
</div>

app/views/clef_tasks/edit.html.erb
<div class="content">
	<div class="masthead">
		<div class="row">
			<div class="info">
        <h6><%= @clef_task.task %></h6>
        <h2>Edit Task</h2>
			</div>
		</div>
	</div>
  <%= render 'form' %>
</div>

app/views/clef_tasks/index.html.erb
<div class='content'>
  <%= render partial: 'organizers/masthead', locals: { organizer: @organizer } %>
  <%= render partial: 'organizers/subnav', locals: { organizer: @organizer, challenges: @challenges } %>

  <div class="row">
    <ul class="list-host-members">
      <% @clef_tasks.each do |task| %>
      <li>
        <div class="details">
          <h5><%= link_to task.task, organizer_clef_task_path(@organizer,task) %></h5>
          <% if policy(task).destroy? %>
            <p class='status active'>
              <%= link_to 'delete',
                    organizer_clef_task_path(@organizer,task),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
            </p>
          <% end %>
        </div>
        <div class="stats">
          <div class="stat-fr">
            <%= task.task_dataset_files.count %><br>
            <span>Dataset Files</span>
          </div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/clef_tasks/new.html.erb
<div class='content'>
  <div class="masthead">
    <div class="row">
      <h2>Create Task</h2>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/clef_tasks/show.html.erb
<div class="content">
  <div class="masthead-detailed">
    <div class="row">
      <div class="info info-challenge">
        <div class="heading-w-icon">
          <h6><%= @clef_task.organizer.organizer %></h6>
          <h2><%= @clef_task.task %></h2>
          <% if policy(@clef_task).edit? %>
            <%= link_to edit_organizer_clef_task_path(@organizer,@clef_task), title: "Edit task" do %>
              <i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </div>
			</div>
    </div>
  </div>

  <div class="sub-nav">
    <div class="row">
      <ul>
        <li>
          <% if @clef_task.eua_file.present? %>
            <%= link_to @clef_task.eua_file.url do %>
              <i class="fa fa-file-pdf-o fa-2x" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </li>
      </ul>
      <%= link_to 'Add Dataset File',
            new_clef_task_task_dataset_file_path(@clef_task),
            class: 'btn btn-primary' %>
    </div>
  </div>

  <div class="row">
    <ul class="list-datasets">
        <%= concept(TaskDataset::Cell::ListDetail, collection: @clef_task.task_dataset_files, current_participant: current_participant) %>
    </ul>
  </div>

</div>