config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get '/robots.txt' => RobotsTxt
  use_doorkeeper

  #get 'test_gauge', to: 'test#gauge'

  admin = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  constraints admin do
    mount Sidekiq::Web => '/sidekiq'
    ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  end

  namespace :api do
    resources :external_graders,
      only: [:create, :show, :update] do
        get :challenge_config, on: :collection
        get :presign, on: :member
        get :submission_info, on: :member
    end
    get 'mailchimps/webhook' => 'mailchimps#verify',
      as: :verify_webhook
    post 'mailchimps/webhook' => 'mailchimps#webhook',
      as: :update_webhook
    resources :clef_tasks, only: [:show]
    get 'user', to: 'oauth_credentials#show'
    resources :challenges, only: [:index, :show] do
      resources :submissions, only: :index
    end
    resources :participants, only: :show
    resources :submissions, only: :show
  end

  namespace :components do
    resources :notifications, only: [:index]
  end

  devise_for :participants
  resources :participants, only: [:show, :edit, :update, :destroy, :index] do
    get :sync_mailchimp
    get :regen_api_key
    get :remove_image
    resources :email_preferences, only: [:edit, :update]
  end
  resources :job_postings, only: [:index, :show]
  resources :gdpr_exports, only: [:create]

  resources :landing_page, only: [:index]
  match '/landing_page/host', to: 'landing_page#host', via: :get

  resources :organizer_applications, only: [:create]
  resources :organizers, except: [:new, :index] do
    resources :challenges
    get :remove_image
    get :regen_api_key
    get :clef_email
    resources :clef_tasks
    resources :members
  end
  resources :blogs do
    resources :votes, only: [:create, :destroy]
  end

  resources :clef_tasks do
    resources :task_dataset_files
  end

  resources :participant_clef_tasks

  resources :task_dataset_files do
    resources :task_dataset_file_downloads
  end

  resources :challenges, only: [:index,:show] do
    resources :dataset_files
    resources :participant_challenges, only: [:index] do
      get :approve, on: :collection
      get :deny, on: :collection
    end
    resources :events
    resources :winners, only: [:index]
    resources :submissions do
      post :filter, on: :collection
    end
    resources :dynamic_contents, only: [:index]
    resources :leaderboards, only: :index do
      get :submission_detail
    end
    resources :topics, except: [:show]
    get :regrade
    get :remove_image
    get :clef_task
    resources :votes, only: [:create, :destroy]
    resources :follows, only: [:create, :destroy]
    resources :invitations, only: [] do
      collection { post :import }
    end
    resources :dataset_terms, only: [:update]
  end
  get '/load_more_challenges', to: 'challenges#load_more', as: :load_more_challenges

  resources :dataset_files, only: [] do
    resources :dataset_file_downloads, only: [:create]
  end

  resources :submissions, only: [] do
    resources :submission_comments, only: [:create, :delete, :edit, :update]
  end

  resources :submission_comments, only: [] do
    resources :votes, only: [:create, :destroy]
  end

  resources :topics do
    resources :comments, only: [:new, :create, :edit, :destroy, :update] do
      get :quote
    end
    resources :votes, only: [:create, :destroy]
  end
  match '/topics/:topic_id/discussion', to: 'comments#new', via: :get, as: :new_topic_discussion


  resources :comments, only: [] do
    resources :votes, only: [:create, :destroy]
  end

  resources :articles do
    resources :article_sections
    resources :votes, only: [:create, :destroy]
    get :remove_image
  end
  get '/load_more_articles', to: 'articles#load_more', as: :load_more_articles

  match '/contact', to: 'pages#contact', via: :get
  match '/privacy', to: 'pages#privacy', via: :get
  match '/terms',   to: 'pages#terms',   via: :get
  match '/faq',     to: 'pages#faq',     via: :get
  match '/cookies', to: 'pages#cookies', via: :get


  resources :markdown_editors, only: [:index, :create] do
    put :presign, on: :collection
  end

  resources :challenge_calls, only: [] do
    resources :challenge_call_responses, only: [:create]
  end
  get '/call-for-challenges/:challenge_call_id/apply' => 'challenge_call_responses#new', as: 'challenge_call_apply'
  get '/call-for-challenges/:challenge_call_id/applications/:id' => 'challenge_call_responses#show', as: 'challenge_call_show'
  get 'SDSC' => 'challenge_call_responses#new', challenge_call_id: 3

  root 'landing_page#index'

  # catch all
  get '*short', to: 'short_urls#show'
end

app/models/topic.rb
class Topic < ApplicationRecord
  include FriendlyId
  friendly_id :topic, use: [:slugged, :finders, :history]
  include ActionView::Helpers::DateHelper
  belongs_to :challenge
  belongs_to :participant, optional: true
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments, reject_if: :all_blank
  has_many :votes, as: :votable

  default_scope { order('created_at desc') }

  validates :topic, presence: true, length: { maximum: 255 }

  def should_generate_new_friendly_id?
    topic_changed?
  end

  def last_activity
    sql = %Q[
      select p.updated_at
      from posts p
      where p.topic_id = #{id}
      order by updated_at desc
    ]
    post = Post.find_by_sql(sql).first
    if post.nil?
      updated = self.updated_at if post.nil?
    else
      updated = post.updated_at
    end
    return time_ago_in_words(updated)
  end

  def participant
    super || NullParticipant.new
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_participant!, except: [:index, :show]
  before_action :set_topic, only: [:edit, :update, :destroy]
  before_action :set_challenge
  after_action :verify_authorized, except: [:index]

  def index
    @topics = @challenge.topics.page(params[:page]).per(20)
  end

  def new
    @topic = @challenge.topics.new
    @comment = @topic.comments.new
    authorize @topic
  end

  def edit
  end

  def create
    @topic = @challenge.topics.new(topic_params)
    authorize @topic
    if @topic.save
      EveryTopicNotificationJob
        .set(wait: 5.minutes)
        .perform_later(@topic.id)
      redirect_to challenge_topics_path(@challenge), notice: 'Topic was successfully created.'
    else
      render :new
    end
  end

  def update
    # https://github.com/norman/friendly_id/issues/185
    if @topic.update(topic_params)
      nested = params['topic']['comment']
      if nested.present?
        comment = Comment.find(nested['id'])
        comment.update(comment_markdown: nested['comment_markdown'])
      end
      redirect_to challenge_topics_path(@challenge), notice: 'Topic was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to challenge_topics_path(@challenge), notice: 'Topic was successfully destroyed.'
  end

  private
    def set_topic
      @topic = Topic.friendly.find(params[:id])
      authorize @topic
    end

    def set_challenge
      @challenge = Challenge.friendly.find(params[:challenge_id])
    end

    def topic_params
      params
        .require(:topic)
        .permit(:challenge_id,
                :participant_id,
                :topic,
                :sticky,
                :views,
                :posts_count,
                comments_attributes: [:id, :comment_markdown, :participant_id])
    end

    def headline_sql
      sql = %Q[
        select p.id, substring(p.post from 0 for 40) as post, p.topic_id, u.name, t.topic as "topic_text"
        from posts p, topics t, participants u
        where p.flagged = false
        and p.topic_id = t.id
        and p.participant_id = u.id
        and t.challenge_id = #{@challenge.id}
        order by p.created_at desc
        limit 1
      ]
    end
end

app/views/topics/_list_header.html.erb
<div class="list-options">
  <p><%= pluralize(((topics.current_page * topics.limit_value ) + (topics.count - topics.limit_value)), 'Topic') %></p>
  <%= link_to 'New Topic', new_challenge_topic_path(challenge), class: 'btn btn-secondary' %>
</div>

app/views/topics/_topics.html.erb
<%= concept(Discussion::Cell::ListDetail,
              collection: @topics,
              current_participant: current_participant) %>

app/views/topics/edit.html.erb
<div class='content'>
  <%= concept(Challenge::Cell::ChallengeMasthead,
                @challenge,
                current_participant: current_participant) %>
  <%= render partial: 'challenges/show/subnav',
        locals: { challenge: @challenge } %>
  <div class='row'>
    <div class="discussion-comment">
      <div class="pic">
        <%= link_to participant_path(current_participant) do %>
        <%= concept(Image::Cell,current_participant) %>
        <% end %>
      </div>
      <%= form_for [@challenge,@topic], html: { class: 'add-comment', id: 'new_comment' } do |f| %>
      <fieldset>
        <label>Topic</label>
        <%= f.text_field :topic %>
        <%= f.fields_for @topic.comments.first do |comment| %>
        <label>Comment</label>
        <%= comment.text_area :comment_markdown, placeholder: "Add a comment...", data: { behavior: "mentions" } %>
        <% if comment.object.persisted? %>
          <%= comment.hidden_field :participant_id, value: comment.object.participant.id %>
        <% else %>
          <%= comment.hidden_field :participant_id, value: current_participant.id %>
        <% end %>
        <%= comment.hidden_field :id %>
        <% end %>
      </fieldset>
      <% if @topic.persisted? %>
        <%= f.hidden_field :participant_id, value: @topic.participant.id %>
      <% else %>
        <%= f.hidden_field :participant_id, value: current_participant.id %>
      <% end %>
      <%= f.submit 'Update topic', class: 'btn btn-primary pull-right' %>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class='content'>
  <%= concept(Challenge::Cell::ChallengeMasthead,
                @challenge,
                current_participant: current_participant) %>
  <%= render partial: 'challenges/show/subnav',
        locals: { challenge: @challenge } %>
  <div class="row">
    <%= render partial: 'list_header',
               locals: { challenge: @challenge, topics: @topics } %>
    <ul class="list-topics">
      <%= render partial: 'topics' %>
    </ul>
    <%= render partial: 'shared/load_more',
               locals: { collection: @topics } %>
  </div>
</div>

app/views/topics/index.js.erb
$(".list-options").replaceWith("<%= j render partial: 'list_header', locals: { challenge: @challenge, topics: @topics } %>");
$(".load-more").remove();
$("ul.list-topics").append("<%= j render partial: 'topics' %>");
$(".list-topics").last().after("<%= j render partial: 'shared/load_more', locals: { collection: @topics } %>");
$('html, body').animate({
   scrollTop: $(document).height()-$(window).height()},
   1400,
   "easeOutQuint"
);

app/views/topics/new.html.erb
<div class='content'>
  <%= concept(Challenge::Cell::ChallengeMasthead,
                @challenge,
                current_participant: current_participant) %>
  <%= render partial: 'challenges/show/subnav',
        locals: { challenge: @challenge } %>
  <%#= concept(Challenge::Cell::ChallengeSubnav,
                @challenge,
                tab: 'discussion',
                current_participant: current_participant) %>
  <div class='row'>
    <div class="discussion-comment">
      <div class="pic">
        <%= link_to participant_path(current_participant) do %>
        <%= concept(Image::Cell,current_participant) %>
        <% end %>
      </div>
        <%= form_for [@challenge,@topic],
            html: {
              class: 'add-comment',
              id: 'new_comment' } do |f| %>
          <fieldset>
            <label>Topic</label>
            <%= f.text_field :topic %>
            <%= f.fields_for :comments do |comment| %>
              <label>Comment</label>
              <%= comment.text_area :comment_markdown,
                    placeholder: "Add a comment...", data: { behavior: "mentions" } %>
              <%= comment.hidden_field :participant_id,
                    value: current_participant.id %>
            <% end %>
          </fieldset>
          <%= f.hidden_field :participant_id,
                value: current_participant.id %>
          <%= f.submit 'Add topic',
                class: 'btn btn-primary pull-right' %>
        <% end %>
    </div>
  </div>
</div>