config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get '/robots.txt' => RobotsTxt
  use_doorkeeper

  #get 'test_gauge', to: 'test#gauge'

  admin = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  constraints admin do
    mount Sidekiq::Web => '/sidekiq'
    ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  end

  namespace :api do
    resources :external_graders,
      only: [:create, :show, :update] do
        get :challenge_config, on: :collection
        get :presign, on: :member
        get :submission_info, on: :member
    end
    get 'mailchimps/webhook' => 'mailchimps#verify',
      as: :verify_webhook
    post 'mailchimps/webhook' => 'mailchimps#webhook',
      as: :update_webhook
    resources :clef_tasks, only: [:show]
    get 'user', to: 'oauth_credentials#show'
    resources :challenges, only: [:index, :show] do
      resources :submissions, only: :index
    end
    resources :participants, only: :show
    resources :submissions, only: :show
  end

  namespace :components do
    resources :notifications, only: [:index]
  end

  devise_for :participants
  resources :participants, only: [:show, :edit, :update, :destroy, :index] do
    get :sync_mailchimp
    get :regen_api_key
    get :remove_image
    resources :email_preferences, only: [:edit, :update]
  end
  resources :job_postings, only: [:index, :show]
  resources :gdpr_exports, only: [:create]

  resources :landing_page, only: [:index]
  match '/landing_page/host', to: 'landing_page#host', via: :get

  resources :organizer_applications, only: [:create]
  resources :organizers, except: [:new, :index] do
    resources :challenges
    get :remove_image
    get :regen_api_key
    get :clef_email
    resources :clef_tasks
    resources :members
  end
  resources :blogs do
    resources :votes, only: [:create, :destroy]
  end

  resources :clef_tasks do
    resources :task_dataset_files
  end

  resources :participant_clef_tasks

  resources :task_dataset_files do
    resources :task_dataset_file_downloads
  end

  resources :challenges, only: [:index,:show] do
    resources :dataset_files
    resources :participant_challenges, only: [:index] do
      get :approve, on: :collection
      get :deny, on: :collection
    end
    resources :events
    resources :winners, only: [:index]
    resources :submissions do
      post :filter, on: :collection
    end
    resources :dynamic_contents, only: [:index]
    resources :leaderboards, only: :index do
      get :submission_detail
    end
    resources :topics, except: [:show]
    get :regrade
    get :remove_image
    get :clef_task
    resources :votes, only: [:create, :destroy]
    resources :follows, only: [:create, :destroy]
    resources :invitations, only: [] do
      collection { post :import }
    end
    resources :dataset_terms, only: [:update]
  end
  get '/load_more_challenges', to: 'challenges#load_more', as: :load_more_challenges

  resources :dataset_files, only: [] do
    resources :dataset_file_downloads, only: [:create]
  end

  resources :submissions, only: [] do
    resources :submission_comments, only: [:create, :delete, :edit, :update]
  end

  resources :submission_comments, only: [] do
    resources :votes, only: [:create, :destroy]
  end

  resources :topics do
    resources :comments, only: [:new, :create, :edit, :destroy, :update] do
      get :quote
    end
    resources :votes, only: [:create, :destroy]
  end
  match '/topics/:topic_id/discussion', to: 'comments#new', via: :get, as: :new_topic_discussion


  resources :comments, only: [] do
    resources :votes, only: [:create, :destroy]
  end

  resources :articles do
    resources :article_sections
    resources :votes, only: [:create, :destroy]
    get :remove_image
  end
  get '/load_more_articles', to: 'articles#load_more', as: :load_more_articles

  match '/contact', to: 'pages#contact', via: :get
  match '/privacy', to: 'pages#privacy', via: :get
  match '/terms',   to: 'pages#terms',   via: :get
  match '/faq',     to: 'pages#faq',     via: :get
  match '/cookies', to: 'pages#cookies', via: :get


  resources :markdown_editors, only: [:index, :create] do
    put :presign, on: :collection
  end

  resources :challenge_calls, only: [] do
    resources :challenge_call_responses, only: [:create]
  end
  get '/call-for-challenges/:challenge_call_id/apply' => 'challenge_call_responses#new', as: 'challenge_call_apply'
  get '/call-for-challenges/:challenge_call_id/applications/:id' => 'challenge_call_responses#show', as: 'challenge_call_show'
  get 'SDSC' => 'challenge_call_responses#new', challenge_call_id: 3

  root 'landing_page#index'

  # catch all
  get '*short', to: 'short_urls#show'
end

app/models/participant.rb
class Participant < ApplicationRecord
  has_merit

  include FriendlyId
  include ApiKey
  include Countries
  friendly_id :name, use: [:slugged, :finders, :history]
  before_save :set_api_key
  before_save { self.email = email.downcase }
  before_save :process_urls
  after_create :set_email_preferences
  after_save :refresh_materialized_view
  after_save :publish_to_prometheus
  mount_uploader :image_file, ImageUploader
  validates :image_file, file_size: { less_than: 5.megabytes }

  devise :confirmable,
    :database_authenticatable,
    :lockable,
    :recoverable,
    :registerable,
    :rememberable,
    :validatable

  default_scope { order('name ASC') }
  belongs_to :organizer, optional: true
  has_many :submissions, dependent: :nullify
  has_many :votes, dependent: :destroy
  has_many :topics, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :articles, dependent: :nullify
  has_many :leaderboards,
    class_name: 'Leaderboard'
  has_many :ongoing_leaderboards,
    class_name: 'OngoingLeaderboard'
  has_many :participant_challenges,
    class_name: 'ParticipantChallenge'
  has_many :challenge_registrations,
    class_name: 'ChallengeRegistration'
  has_many :participant_challenge_counts,
    class_name: 'ParticipantChallengeCount'
  has_many :challenge_organizer_participants,
    class_name: 'ChallengeOrganizerParticipant'
  has_many :base_leaderboards, dependent: :nullify
  has_many :challenges,
    through: :participant_challenges
  has_many :dataset_file_downloads,
    dependent: :destroy
  has_many :task_dataset_file_downloads,
    dependent: :destroy
  has_many :email_preferences,
    dependent: :destroy
  has_many :email_preferences_tokens,
    dependent: :destroy
  has_many :follows,
    dependent: :destroy
  has_many :participant_clef_tasks,
    dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :access_grants,
    class_name: "Doorkeeper::AccessGrant",
    foreign_key: :resource_owner_id,
    dependent: :destroy
  has_many :access_tokens,
    class_name: "Doorkeeper::AccessToken",
    foreign_key: :resource_owner_id,
    dependent: :destroy

  validates :email,
    presence: true,
    'valid_email_2/email': true,
    uniqueness: { case_sensitive: false }
  validates :website, :url => { allow_blank: true }
  validates :github, :url => { allow_blank: true }
  validates :linkedin, :url => { allow_blank: true }
  validates :twitter, :url => { allow_blank: true }
  validates :name,
    format: {
      with: /[a-zA-Z0-9\-_]/,
      message: 'cannot contain spaces or special characters'
    },
    length: { minimum: 2 },
    uniqueness: { case_sensitive: false }

  #validates :name,
  #  length: { minimum: 2 },
  #  uniqueness: { case_sensitive: false }
  validates :affiliation,
    length: { in: 2...100},
    allow_blank: true
  validates :country_cd,
    inclusion: { in: ISO3166::Country::codes}, allow_blank: true
  validates :address,
    length: { in: 10...255 },
    allow_blank: true
  validates :first_name,
    length: { in: 2...100},
    allow_blank: true
  validates :last_name,
    length:{ in: 2...100},
    allow_blank: true

  def disable_account(reason)
    self.update(
      account_disabled: true,
      account_disabled_reason: reason,
      account_disabled_dttm: Time.now )
  end

  def enable_account
    self.update(
      account_disabled: false,
      account_disabled_reason: nil,
      account_disabled_dttm: nil )
  end

  def active_for_authentication?
    super && self.account_disabled == false
  end

  def inactive_message
    if account_disabled
      "Your account has been disabled. Please contact us at info@crowdai.org."
    end
  end

  def admin?
    admin
  end

  def online?
    updated_at > 10.minutes.ago
  end

  def avatar
    image.try(:image)
  end

  def avatar_medium_url
    if image.present?
      image.image.url(:medium)
    else
      "//#{ENV['HOST']}/assets/image_not_found.png"
    end
  end

  def image_url
    if image_file.file.present?
      image_url = image_file.url
    else
      image_url = 'users/avatar-default.png'
    end
  end

  def process_urls
    ['website','github','linkedin','twitter'].each do |url_field|
      format_url(url_field)
    end
  end

  def format_url(url_field)
    if self.send(url_field).present?
      unless self.send(url_field).include?("http://") || self.send(url_field).include?("https://")
        self.send("#{url_field}=", "http://#{self.send(url_field)}")
      end
    end
  end

  def after_confirmation
    super
    AddToMailChimpListJob.perform_later(self.id)
  end

  def set_email_preferences
    self.email_preferences.create!
  end

  def should_generate_new_friendly_id?
    name_changed?
  end

  def self.find_by(args)
    super || NullParticipant.new
  end

  def self.find(args)
    begin
      super
    rescue
      NullParticipant.new
    end
  end

  def refresh_materialized_view
    if saved_change_to_attribute?(:organizer_id)
      RefreshChallengeOrganizerParticipantViewJob.perform_later
    end
  end

  def publish_to_prometheus
    Prometheus::ParticipantCounterService.new.call
  end

end

app/controllers/api/participants_controller.rb
class Api::ParticipantsController < Api::BaseController
  before_action :auth_by_admin_api_key
  respond_to :json

  def show
    @participant = Participant
      .where("lower(name) = '#{params[:id].downcase}'").first
    if @participant.present?
      payload = Api::ParticipantSerializer.new(@participant).as_json
      payload.merge({ message: 'Participant found.'})
      status = :ok
    else
      payload = { message: "No participant could be found for this username" }
      status = :not_found
    end
    render json: payload, status: status
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :authenticate_participant!, except: [:show]
  before_action :set_participant,
    only: [:show, :edit, :update, :destroy]

  respond_to :html, :js

  def show
    @articles = Article.where(participant_id: @participant.id)
    challenge_ids = policy_scope(ParticipantChallenge)
      .where(participant_id: @participant.id)
      .pluck(:challenge_id)
    @challenges = Challenge.where(id: challenge_ids)
    @posts = @participant.comments.order(created_at: :desc)
  end

  def edit
  end

  def index
    @participants = Participant.all
  end

  def update
    @participant = Participant.friendly.find(params[:id])
    if @participant.update_attributes(participant_params)
      flash[:success] = "Profile updated"
      redirect_to @participant
    else
      render :edit
    end
  end

  def destroy
    @participant.destroy
    redirect_to '/', notice: 'Account was successfully deleted.'
  end


  def regen_api_key
    @participant = Participant.friendly.find(params[:participant_id])
    authorize @participant
    @participant.api_key = @participant.generate_api_key
    @participant.save!
    redirect_to participant_path(@participant),notice: 'API Key regenerated.'
  end

  def sync_mailchimp
    @job = AddToMailChimpListJob.perform_later(params[:participant_id])
    render 'admin/participants/refresh_sync_mailchimp_job_status'
  end

  def remove_image
    @participant = Participant.friendly.find(params[:participant_id])
    authorize @participant
    @participant.remove_image_file!
    @participant.save
    redirect_to edit_participant_path(@participant),
      notice: 'Image removed.'
  end

  private
  def set_participant
    @participant = Participant.friendly.find(params[:id])
    authorize @participant
  end

  def participant_params
    params
      .require(:participant)
      .permit(
        :email,
        :password,
        :password_confirmation,
        :phone_number,
        :name,
        :organizer_id,
        :email_public,
        :bio,
        :website,
        :github,
        :linkedin,
        :twitter,
        :image_file,
        :affiliation,
        :address,
        :city,
        :country_cd,
        :first_name,
        :last_name)
    end


end

app/helpers/participants_helper.rb
module ParticipantsHelper

  def avatar_url(participant, size)
    if participant.avatar
      if size == 'profile'
        participant.avatar.url('thumbnail')
      else
        participant.avatar.url(size)
      end
    else
      'https://www.gravatar.com/avatar/?d=mm&s=200'
    end
  end
  # usage:  <%= image_tag avatar_url(user,'medium'), class: "img-responsive" %>
  #         <%= image_tag avatar_url(user,'thumbnail') %>

  def participant_link(participant)
    participant.is_a?(NullParticipant) ? '#' : participant_path(participant)
  end
end

app/views/participants/edit.html.erb
<div class='content'>
  <div class="masthead">
    <div class="row">
      <div class="info">
        <h2>Edit Profile</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <%= form_for @participant, validate: false, html: { class: "sgl-col" } do |f| %>
    <fieldset>
      <label>Username</label>
      <%= f.text_field :name %>
      <label>First name</label>
      <%= f.text_field :first_name %>
      <label>Last name</label>
      <%= f.text_field :last_name %>

      <label>Personal Data</label>
      <p id='gdpr-text'>Download your personal data that has been collected by crowdAI.</p>
      <div class="button-group">
        <%= link_to 'Download',
              gdpr_exports_path,
              method: :post, remote: true,
              id: 'gdpr-button',
              class: 'btn btn-primary' %>
      </div>
      <br/>

      <label>Profile Picture</label>
      <div class="upload">
        <%= concept(Image::Cell,
                        @participant,
                        klass: 'img-thumb',
                        current_participant: current_participant) %>
        <%#= f.file_field :profile_image,
              multiple: false,
              direct_upload: true,
              options: { class: 'file-upload' } %>

        <%= f.file_field :image_file, class: 'file-upload' %>
        <% if @participant.image_file.present? %>
          <%= link_to 'Delete', participant_remove_image_path(@participant) %>
        <% end %>
        <span>Your image will be cropped if necessary. 5MB limit</span>
      </div>
      <label>Affiliation</label>
      <%= f.text_field :affiliation %>
      <label>Address</label>
      <%= f.text_field :address %>
      <label>City</label>
      <%= f.text_field :city %>
      <label>Country</label>
      <%= f.country_select :country_cd, { include_blank: '--- Select a country ---'}, { class: 'country-select-box' }  %>
      <label>Bio</label>
      <%= f.text_area :bio %>
      <label>Github</label>
      <%= f.text_field :github, placeholder: "URL (e.g. www.github.com/crowdai)", class: 'url' %>
      <label>LinkedIn</label>
      <%= f.text_field :linkedin, placeholder: "URL (e.g. www.linkedin.com/in/crowdai)", class: 'url' %>
      <label>Twitter</label>
      <%= f.text_field :twitter, placeholder: "URL (e.g. www.twitter.com/crowdai)", class: 'url' %>
      <label>Website</label>
      <%= f.text_field :website, placeholder: "URL (e.g. www.crowdai.org)", class: 'url' %>
      <div class="button-group">
        <%= f.button "Save", class: 'btn btn-primary' %>
        <%= link_to 'Cancel', participant_path(@participant), class: "btn btn-secondary" %>
      </div>
    </fieldset>
    <% end %>
  </div>
</div>

app/views/participants/show.html.erb
<div class='content'>
  <%= concept(Participant::Cell::ParticipantMasthead,
                @participant,
                current_participant: current_participant) %>

  <div class="sub-nav">
    <div class="row">
      <ul class='tabs'>
        <li data-tab='tab-challenges' class="active">
          <a href="#" onclick="return false;">Challenges
            <sup><%= @challenges.count unless @challenges.count == 0 %></sup>
          </a>
        </li>
        <li data-tab='tab-articles'>
          <a href="#" onclick="return false;">Tutorials
            <sup><%= @articles.count unless @articles.count == 0%></sup>
          </a>
        </li>
        <li data-tab='tab-posts'>
          <a href="#" onclick="return false;">Posts
            <sup><%= @posts.count unless @posts.count == 0 %></sup>
          </a>
        </li>
        <li data-tab='tab-bio'>
          <a href="#" onclick="return false;">Bio</a>
        </li>
        <% if policy(@participant).clef_access? %>
          <li data-tab='tab-contact-info'>
            <a href="#" onclick="return false;">Contact</a>
          </li>
        <% end %>
        <% if current_participant && current_participant.admin? %>
          <li data-tab='tab-badges'>
            <a href="#" onclick="return false;">Badges</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div id='tab-challenges' class='tab-content active'>
    <div class="row">
      <% if @challenges.any? %>
      <ul class="list-challenges">
        <%= concept(Challenge::Cell::ListDetail,
                        collection: @challenges,
                        current_participant: current_participant) %>
      </ul>
    <% else %>
      <div class='article'>
        <p class='light'>
          <%= "#{@participant.name} hasn't entered any challenges yet..." %>
        </p>
      </div>
      <% end %>
    </div>
  </div>

  <div id='tab-articles' class='tab-content'>
    <div class="row">
      <% if @articles.any? %>
        <ul class="list-tutorials">
         <% @articles.each do |article| %>
           <%= render partial: 'articles/article', locals: { article: article } %>
         <% end %>
        </ul>
      <% else %>
        <div class='article'>
          <p class='light'>
            <%= "#{@participant.name} hasn't authored any tutorials yet..." %>
          </p>
        </div>
      <% end %>
    </div>
  </div>

  <div id='tab-posts' class='tab-content'>
    <div class="row">
      <% if @posts.any? %>
      <ul class="list-tutorials">
        <%= concept(Discussion::Cell::ParticipantComment,
                          collection: @posts,
                          current_participant: current_participant) %>
      </ul>
    <% else %>
      <div class='article'>
        <p class='light'>
          <%= "#{@participant.name} hasn't made any posts yet..." %>
        </p>
      </div>
      <% end %>
    </div>
  </div>

  <div id='tab-bio' class='tab-content'>
    <div class="row">
      <div class="article">
        <% if @participant.bio.present? %>
        <%= @participant.bio %>
      <% else %>
        <p class='light'>
          <%= "Apparently #{@participant.name} prefers to keep an air of mystery about them..." %>
        </p>
        <% end %>
      </div>
    </div>
  </div>

  <% if policy(@participant).clef_access? %>
      <div id='tab-contact-info' class='tab-content'>
        <div class="row">
          <div class="article">
            <table>
              <tr>
                <td>First name:</td>
                <td>
                <% if @participant.first_name.present? %>
                  <%= @participant.first_name %>
                <% else %>
                  <span class="light">Not specified yet</span>
                <% end %>
                </td>
              </tr>
              <tr>
                <td>Last name:</td>
                <td>
                <% if @participant.last_name.present? %>
                  <%= @participant.last_name %>
                <% else %>
                  <span class="light">Not specified yet</span>
                <% end %>
                </td>
              </tr>
              <tr>
                <td>Email:</td>
                <td><%= @participant.email %></td>
              </tr>
              <tr>
                <td>Address:</td>
                <td>
                  <% if @participant.address.present? %>
                    <%= @participant.address %>
                  <% else %>
                    <span class="light">Not specified yet</span>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td>City:</td>
                <td>
                  <% if @participant.city.present? %>
                    <%= @participant.city %>
                  <% else %>
                    <span class="light">Not specified yet</span>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td>Country:</td>
                <td>
                  <% if @participant.country_cd.present? %>
                    <%= "#{ISO3166::Country.find_country_by_alpha2(@participant.country_cd)} (#{@participant.country_cd})" %>
                  <% else %>
                    <span class="light">Not specified yet</span>
                  <% end %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
  <% end %>

  <% if current_participant && current_participant.admin? %>
    <div id='tab-badges' class='tab-content'>
      <div class="row">
        <div class="article">
          <% if @participant.badges.present? %>
            <ul>
              <% @participant.badges.each do |badge| %>
                <li class='badge badge-accent'>
                  <%= badge.name %><br/>
                  <%= badge.description %>
                </li>
              <% end %>
            </ul>
          <% else %>
            <p class='light'>
              No badges yet.
            </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

</div><!-- .content -->